server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8765/eureka/

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: userModule
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
        - id: orderModule
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**